import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { AgentManifest } from "../core/types.js";
import { loadTemplate } from "./utils.js";

/**
 * Generate Docker packaging files from Agent Manifest
 */
export function generateDocker(manifest: AgentManifest, outputDir: string): void {
  const dockerDir = join(outputDir, "docker");
  mkdirSync(dockerDir, { recursive: true });

  // Determine port from REST config or default
  const port = 3000;

  // Generate environment variables from manifest
  const envVars: string[] = [];
  if (manifest.runtime?.env) {
    for (const env of manifest.runtime.env) {
      const value = env.secret ? "" : `      - ${env.name}=${env.value || ""}`;
      if (value) {
        envVars.push(value);
      }
    }
  }

  // Generate Dockerfile
  const dockerfileCode = loadTemplate("Dockerfile.template", {
    agentName: manifest.name,
    version: manifest.version,
    port: String(port),
  }, "docker");

  writeFileSync(join(dockerDir, "Dockerfile"), dockerfileCode);

  // Generate docker-compose.yml
  const composeCode = loadTemplate("docker-compose.yml.template", {
    agentKebabName: manifest.name.replace(/_/g, "-").toLowerCase(),
    agentName: manifest.name,
    version: manifest.version,
    port: String(port),
    envVars: envVars.join("\n"),
  }, "docker");

  writeFileSync(join(dockerDir, "docker-compose.yml"), composeCode);

  // Generate package.json (combined deps)
  const pkgCode = loadTemplate("package.json.template", {
    agentKebabName: manifest.name.replace(/_/g, "-").toLowerCase(),
    agentName: manifest.name,
    version: manifest.version,
  }, "docker");

  writeFileSync(join(dockerDir, "package.json"), pkgCode);

  // Generate README
  const readmeCode = generateReadme(manifest);
  writeFileSync(join(dockerDir, "README.md"), readmeCode);

  console.log(`  ✅ Docker packaging generated in ${dockerDir}/`);
  console.log(`     • Dockerfile — multi-stage build`);
  console.log(`     • docker-compose.yml — orchestration`);
  console.log(`     • package.json — combined dependencies`);
  console.log(`     • README.md — deployment instructions`);
}

function generateReadme(manifest: AgentManifest): string {
  const imageName = manifest.name.replace(/_/g, "-").toLowerCase();

  return `# ${manifest.displayName || manifest.name} Docker Deployment

> Auto-generated by AgentPackager

## Quick Start

\`\`\`bash
cd docker/
docker-compose up --build
\`\`\`

Server starts on http://localhost:3000

## Build Only

\`\`\`bash
# Build image
docker build -t ${imageName}:${manifest.version} .

# Run container
docker run -p 3000:3000 ${imageName}:${manifest.version}
\`\`\`

## Security Features

- **Non-root user**: Runs as \`agent\` (UID 1001)
- **Read-only filesystem**: Container filesystem is read-only
- **No new privileges**: \`security_opt: no-new-privileges:true\`
- **Tmpfs**: /tmp mounted as tmpfs with noexec,nosuid
- **Health check**: Built-in HTTP health check on /health

## Environment Variables

| Variable | Description |
|----------|-------------|
| NODE_ENV | production |
| PORT | 3000 |

## Push to Registry

\`\`\`bash
# Tag for registry
docker tag ${imageName}:${manifest.version} registry.example.com/${imageName}:${manifest.version}

# Push
docker push registry.example.com/${imageName}:${manifest.version}
\`\`\`

## Scale

\`\`\`bash
# Scale to 3 instances
docker-compose up --scale ${imageName}=3
\`\`\`
`;
}
